var UserSQL = {
	//用户注册
    AddAccount: 'INSERT INTO user(account,UserIp,LoginTime,SocketId,grade,coin,exp_now,hero1,hero2,hero3,cheat,OnlineTime) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)', // 插入数据
	SelectAccount: 'select account from user where LoginTime in (select max(LoginTime) from user where UserIp=?)',
	SelectSocketId:'select SocketId from user where account=?',
	UpdateSocketId:'update user set SocketId=?,LoginTime=? where account=?',
	RegisterAccount:'select * from user where account=?',
	SelectSocketId:'select SocketId from user where account=?',
	UpdateIp:'update user set UserIp=?,LoginTime=?,SocketId=? where account=?',
	SelectName:'select name from user where account=?',
	SelectLevelStar:'select level_id,star,star1,star2,star3 from user_level where account=?',
	UpdateHero:'update user set hero1=?,hero2=?,hero3=? where account=?',
	GoodsConsume:'update bag set goods_count=goods_count-? where account=? and goods_id=?',
	CoinConsume:'update user set coin=coin-? where account=?',
	SelectGoods:'select goods_id,goods_count from bag where account=?',
	
	SelectLevel:'select star from user_level where account=? and level_id=?',
	SelectStar:'select star from user_level where level_id=?and account=?',
	//AddLevel:'insert into user_level(account,level_id,star) values(?,?,?)',
	//UpdateStar:'update user_level set star=?where level_id=?and account=?',
	SelectMaxLevel:'select max(level_id) from user_level where account=?',
	AddGoods:'insert into bag(account,goods_id,goods_count) values(?,?,?)',
	//var SelectGoods='select goods_count from bag where account='+Account+'and goods_id='+goods;
	UpdateGoods:'update bag set goods_count=goods_count+? where account=?and goods_id=?',
	SelectExp:'select exp_now from user where account=?',
	UpdateRoleGrade:'update users_roles set role_grade=? where account=? and role_id=?',
	UpdateHeroExp:'update users_roles set role_exp=? where account=? and role_id=?',
	UpdateCoin:'update user set coin=coin+? where account=?',
	SelectHeroGrade:'select role_grade from users_roles where account=? and role_id=?',
	SelectHero:'select hero1,hero2,hero3 from user where account=?',
	SelectHeroExp:'select role_exp from users_roles where account=? and role_id=?',
	//SelectHeroSkill:'select skill1,skill2,skill3 from users_roles where account=? and role_id=?',
	SelectHeroSkillCD:'select skill_cooldown from skill where skill_id=?',
	SelectHeroSkillDamage:'select skill_damage from skill where skill_id=?',
	UpdateCheat:'update user set cheat=cheat+? where account=?',
	AddHero:'insert into users_roles(account,role_id,role_grade,role_exp) value(?,?,?,?)',
	SelectOwnHero:'select role_id,role_grade,role_exp from users_roles where account=?',
	SelectHeroNextGradeExp:'select role_exp from role_levels where role_id=? and role_grade=?',
	SelectHeroHpDamage:'select hp,damage from role_levels where role_id=? and role_grade=?',
	AddLevelStar:'insert into user_level(account,level_id,star,star1,star2,star3) value(?,?,?,?,?,?)',
	UpdateLevelStar:'update user_level set star=?,star1=?,star2=?,star3=? where level_id=? and account=?',
	UserLoginTime:'select LoginTime from user where account=?',
	UpdateUserOnlineTime:'update user set OnlineTime=OnlineTime+? where account=?',
	AddUserName:'update user set name=? where account=?',
	SelectGoodsCount:'select goods_count from bag where goods_id=? and account=?',
	UpdateLevelStarFlag:'update user_level set star1=?,star2=?,star3=? where level_id=? and account=?',
	SelectLevelStarSum:'select *from user_level where account=? and level_id like ?',
	UpdateBigLevelStar:'update award_level set star=star+? where account=? and level_id=?',
	SelectBigLevelStar:'select star from award_level where account=? and level_id=?',
	SelectHeroPlay:'select hero1,hero2,hero3 from user where account=?',
	AddBigLevelStar:'insert into award_level(account,level_id,star,award_star6,award_star9) value(?,?,?,?,?)',
	};

module.exports = UserSQL;